name: Deploy to WP Engine
on:
    push:
        branches: [dev, stg, main]

jobs:
    deploy-prod:
        name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: choctaw-nation/shared-github-actions/.github/workflows/deploy.yml@1.1.0
        with:
            WPE_ENV: twmprod
            theme_name: together-were-more
        secrets: inherit

    deploy-stg:
        name: Deploy to Staging
        if: github.ref == 'refs/heads/stg'
        uses: choctaw-nation/shared-github-actions/.github/workflows/deploy.yml@1.1.0
        with:
            WPE_ENV: twmstg
            theme_name: together-were-more
        secrets: inherit

    deploy-dev:
        name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        uses: choctaw-nation/shared-github-actions/.github/workflows/deploy.yml@1.1.0
        with:
            WPE_ENV: cnotwmdev
            theme_name: together-were-more
        secrets: inherit

    # Run Playwright tests on Dev
    # test-dev:
    #     name: Run Playwright Tests on Development
    #     needs: deploy-dev
    #     uses: ./.github/workflows/playwright.yml
    #     with:
    #         ref: ${{ github.ref }}
    #     secrets: inherit

    # Run Playwright tests on Staging
    # test-stg:
    #     name: Run Playwright Tests on Staging
    #     needs: deploy-stg
    #     uses: ./.github/workflows/playwright.yml
    #     with:
    #         ref: ${{ github.ref }}
    #     secrets: inherit
